name: compile_dart2js
description: A sample command-line application with basic argument parsing.
version: 1.0.0
repository: https://github.com/altynbek132/compile_dart2js
publish_to: none

executables:
  compile_dart2js:

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  glob: ^2.1.2

  utils:
    git:
      url: https://github.com/altynbek132/flutter_util_packages
      path: packages/utils

dev_dependencies:
  flutter_lints: ^3.0.2
  lints: ^3.0.0
  test: ^1.24.0
