name: compile_dart2js
description: A sample command-line application with basic argument parsing.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

executables:
  compile_dart2js:

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  glob: ^2.1.2

dev_dependencies:
  flutter_lints: ^3.0.2
  lints: ^3.0.0
  test: ^1.24.0
